"""baseline

Revision ID: c5967048d886
Revises: 
Create Date: 2026-04-30 11:52:16.209606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5967048d886'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('admin_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('follower_counts', sa.JSON(), nullable=False),
    sa.Column('niche_tags', sa.JSON(), nullable=False),
    sa.Column('audience_region', sa.String(length=50), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('successful_post_count', sa.Integer(), nullable=False),
    sa.Column('earnings_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('earnings_balance_cents', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earned_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('political_campaigns_enabled', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('scraped_profiles', sa.JSON(), nullable=False),
    sa.Column('ai_detected_niches', sa.JSON(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_remaining', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout_rules', sa.JSON(), nullable=False),
    sa.Column('targeting', sa.JSON(), nullable=False),
    sa.Column('content_guidance', sa.Text(), nullable=True),
    sa.Column('campaign_goal', sa.String(length=30), nullable=True),
    sa.Column('campaign_type', sa.String(length=20), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('preferred_formats', sa.JSON(), nullable=False),
    sa.Column('disclaimer_text', sa.Text(), nullable=True),
    sa.Column('penalty_rules', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_urls', sa.JSON(), nullable=False),
    sa.Column('ai_generated_brief', sa.Boolean(), nullable=False),
    sa.Column('budget_exhaustion_action', sa.String(length=20), nullable=False),
    sa.Column('budget_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('screening_status', sa.String(length=20), nullable=False),
    sa.Column('campaign_version', sa.Integer(), nullable=False),
    sa.Column('invitation_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('expired_count', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_company_id'), 'campaigns', ['company_id'], unique=False)
    op.create_index(op.f('ix_campaigns_screening_status'), 'campaigns', ['screening_status'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('company_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_transactions_company_id'), 'company_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_transactions_stripe_session_id'), 'company_transactions', ['stripe_session_id'], unique=True)
    op.create_table('admin_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('concerns_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_review_queue_campaign_id'), 'admin_review_queue', ['campaign_id'], unique=False)
    op.create_table('campaign_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content_mode', sa.String(length=20), nullable=False),
    sa.Column('payout_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignment_expires_at', 'campaign_assignments', ['expires_at'], unique=False)
    op.create_index('ix_assignment_user_status', 'campaign_assignments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_campaign_assignments_campaign_id'), 'campaign_assignments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_assignments_user_id'), 'campaign_assignments', ['user_id'], unique=False)
    op.create_table('campaign_invitation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_invitation_log_campaign_id'), 'campaign_invitation_log', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_invitation_log_user_id'), 'campaign_invitation_log', ['user_id'], unique=False)
    op.create_index('ix_invitation_log_campaign_user', 'campaign_invitation_log', ['campaign_id', 'user_id'], unique=False)
    op.create_table('campaign_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('post_order', sa.Integer(), nullable=False),
    sa.Column('scheduled_offset_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_posts_campaign_id'), 'campaign_posts', ['campaign_id'], unique=False)
    op.create_table('content_screening_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_keywords', sa.JSON(), nullable=False),
    sa.Column('screening_categories', sa.JSON(), nullable=False),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.Column('review_result', sa.String(length=20), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_screening_logs_campaign_id'), 'content_screening_logs', ['campaign_id'], unique=True)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_campaign_id'), 'payouts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_payouts_user_id'), 'payouts', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['campaign_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_assignment_id'), 'posts', ['assignment_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_post_id'), 'metrics', ['post_id'], unique=False)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appealed', sa.Boolean(), nullable=False),
    sa.Column('appeal_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalties_user_id'), 'penalties', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penalties_user_id'), table_name='penalties')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_metrics_post_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_posts_assignment_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_payouts_user_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_campaign_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_content_screening_logs_campaign_id'), table_name='content_screening_logs')
    op.drop_table('content_screening_logs')
    op.drop_index(op.f('ix_campaign_posts_campaign_id'), table_name='campaign_posts')
    op.drop_table('campaign_posts')
    op.drop_index('ix_invitation_log_campaign_user', table_name='campaign_invitation_log')
    op.drop_index(op.f('ix_campaign_invitation_log_user_id'), table_name='campaign_invitation_log')
    op.drop_index(op.f('ix_campaign_invitation_log_campaign_id'), table_name='campaign_invitation_log')
    op.drop_table('campaign_invitation_log')
    op.drop_index(op.f('ix_campaign_assignments_user_id'), table_name='campaign_assignments')
    op.drop_index(op.f('ix_campaign_assignments_campaign_id'), table_name='campaign_assignments')
    op.drop_index('ix_assignment_user_status', table_name='campaign_assignments')
    op.drop_index('ix_assignment_expires_at', table_name='campaign_assignments')
    op.drop_table('campaign_assignments')
    op.drop_index(op.f('ix_admin_review_queue_campaign_id'), table_name='admin_review_queue')
    op.drop_table('admin_review_queue')
    op.drop_index(op.f('ix_company_transactions_stripe_session_id'), table_name='company_transactions')
    op.drop_index(op.f('ix_company_transactions_company_id'), table_name='company_transactions')
    op.drop_table('company_transactions')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_screening_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_company_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
